server:
  port: 8085

spring:
  application:
    name: nacos-consumer

  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848