server:
  port: 8871

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring_cloud_dubbo_server

dubbo:
  application:
    name: spring-cloud-dubbo-server
    id: spring-cloud-dubbo-server
  protocol:
    id: dubbo
    port: 20990
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    username: nacos
    password: nacos
  provider:
    version: 1.0.0
    group: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'